add limited settings
RedHatInsights/cloud-services-config pull request #102
Opened 2019-12-10 18:14 UTC by ryelo

We only want to expose settings/applications/insights for now. Other apps will be following later.

2019-12-11 14:34 UTC, kruai approved these changes

2019-12-12 20:00 UTC, ryelo commented
Good to merge on 13 December

2019-12-16 14:50 UTC, kruai commented
@ryelo Can you update this PR with the newer structure of Settings that we have on prod-beta? That should allow it to be merged to Stable without issue

2019-12-16 15:10 UTC, kruai requested changes
Explicitly marking as "Request changes" so this doesn't get merged before the config gets updated.

2019-12-16 15:27 UTC, closed without merging