fix nav structure
RedHatInsights/cloud-services-config pull request #113
Opened 2020-01-31 13:39 UTC by ryelo

**Jira**
https://projects.engineering.redhat.com/browse/RHCLOUD-4310

Nav structure should look like:
https://marvelapp.com/5dcjg6g/screen/63628276

2020-01-31 14:22 UTC, karelhala requested changes

2020-01-31 14:22 UTC, karelhala commented on main.yml
> +      - id: Users
Lower case id and upper case title.

2020-01-31 14:23 UTC, ryelo commented on main.yml
> +      - id: Users
good catch 😄

2020-01-31 14:34 UTC, karelhala approved these changes

2020-01-31 14:41 UTC, kruai approved these changes

2020-01-31 14:45 UTC, ryelo commented
Keeping this on hold. There's a question about whether to use `User access` or `User access management`

2020-01-31 19:39 UTC, karelhala approved these changes

2020-01-31 19:44 UTC, kruai approved these changes

2020-01-31 19:44 UTC, kruai commented
LGTM

2020-02-03 14:12 UTC, kruai approved these changes
lol

2020-02-03 14:23 UTC, merged