Side nav changes
RedHatInsights/cloud-services-config pull request #1188
Opened 2022-05-17 18:14 UTC by h-kataria

- changed urls from ansible/insights/ to ansible/automation-analytics

https://issues.redhat.com/browse/AA-1114

2022-05-18 06:34 UTC, Hyperkid123 requested changes, later dismissed
The `automationAnalytics` module does not have route registered for `/ansible/automation-analytics`

Can you please update the `fed-modules.json` file?

2022-05-18 08:34 UTC, karelhala reviewed
You should also update `automationAnalytics` federated module in `fed-mods.json` with `/ansible/automation-analytics` route. Otherwise this will throw an error of unknown application. Can we also test this on `prod-beta` first? A different PR to prod-beta would be required so we can test if everything works and perhaps could roll back if it would throw some errors.

2022-05-19 07:00 UTC, Hyperkid123 commented on chrome/fed-modules.json
>                      "/ansible/reports",
What about the rest of the routes on the list? Is the automation analytics app supposed to render there? I would guess no based on the links from the nav.

2022-05-19 13:12 UTC, h-kataria commented on chrome/fed-modules.json
>                      "/ansible/reports",
@Hyperkid123 not sure how are they working currently in that case, I was confused hence did not change rest of them

2022-05-19 14:28 UTC, Hyperkid123 commented on chrome/fed-modules.json
>                      "/ansible/reports",
OK lest take clean them up in another PR

2022-06-02 14:33 UTC, karelhala approved these changes

2022-06-02 14:34 UTC, merged