Add Notifications to AA subnav.
RedHatInsights/cloud-services-config pull request #135
Opened 2020-03-13 17:13 UTC by kialam

2020-03-24 20:12 UTC, kruai requested changes

2020-03-24 20:12 UTC, kruai commented on main.yml
> +      - id: clusters
Was this change intended as well?

2020-03-25 13:57 UTC, kialam commented on main.yml
> +      - id: clusters
@kruai yes

2020-03-25 14:34 UTC, kruai commented on main.yml
> +      - id: clusters
OK, just making sure. Merging now

2020-03-25 14:34 UTC, kruai approved these changes

2020-03-25 14:34 UTC, merged

2020-03-25 15:31 UTC, kialam commented on main.yml
> +      - id: clusters
Thank you!