Add ACS to left navbar for customers
RedHatInsights/cloud-services-config pull request #1378
Opened 2023-01-17 18:36 UTC by kylape

Now that ACS is doing field trials, it should show up in the left navbar for customers, not just folks with @redhat.com email addresses.

cc @vjwilson @sachaudh @rukletsov

2023-01-17 18:40 UTC, kylape commented
please hold off on merging until one of the three cc'd folks confirm this is what we want.

2023-01-17 19:25 UTC, vjwilson requested changes
It's my understanding that we need to limit access to this to customers who filled out a request form. (I'm not sure if there's any contractual issues--like an NDA--but I want reassurance before we take this step.)

2023-01-17 21:58 UTC, vjwilson approved these changes
Doron says release it to the world.

2023-01-18 09:17 UTC, Hyperkid123 approved these changes

2023-01-18 09:18 UTC, merged