Adds ansible bundle
RedHatInsights/cloud-services-config pull request #36
Opened 2019-08-26 20:43 UTC by tahmidefaz

2019-08-26 20:44 UTC, tahmidefaz commented
Looks like they don't have a deploy repo setup already. Hence, there's no mention of it. Let me know if I need to change anything!

2019-08-26 20:51 UTC, kruai requested changes
You might only need the title change, but I'm not going to approve just yet; I'm debugging an issue with Ryan F and the config in your PR looks very similar. Once I figure out what's happening with `/migrations`, I'll approve or request more changes

2019-08-26 20:51 UTC, kruai commented on main.yml
> +    title: Ansible
`frontend.title` is an override; you only need it if you need the UI to display the name differently than the main `title` field.

2019-08-27 13:16 UTC, ryandillinfelton reviewed
Looks fine to me. I'll come take a look again after we figure out what's going on with the migrations bundle so we can make sure it won't happen with this too

2019-08-28 14:01 UTC, kruai approved these changes
Now that we know migration-analytics is actually correct, I think this one is going to work fine.

2019-08-28 14:05 UTC, ryelo approved these changes

2019-08-28 17:21 UTC, ryandillinfelton approved these changes
LGTM

2019-08-28 17:32 UTC, merged

2019-08-28 17:32 UTC, kruai commented
Your wish is my command